### ISSUE TITLE
When trying to refresh token, I get this error "AADB2C90080: The provided grant has expired. Please re-authenticate and try again"

### ISSUE THREAD

**Issue by Rajashekhargouda** [AzureAD/microsoft-authentication-library-for-android#1004]
**Describe the bug**
When I am trying to refresh the token by calling acquireTokenSilentAsync, I am getting the below error:
AADB2C90080: The provided grant has expired. Please re-authenticate and try again. Current time: 1587023649, Grant issued time: 1586869378, Grant expiration time: 1586955778
Correlation ID: <Correlation ID>
Timestamp: 2020-04-16 07:54:09Z

And unable to refresh the token

**Smartphone (please complete the following information):**
 - Device: [e.g. MI A3]
 - Android Version: [e.g.  Android Pie(9)]
 - MSAL Version - 0.2.2

**Stacktrace**
com.microsoft.identity.client.exception.MsalUiRequiredException: AADB2C90080: The provided grant has expired. Please re-authenticate and try again. Current time: 1587024319, Grant issued time: 1586869378, Grant expiration time: 1586955778
Correlation ID: <Correlation ID>
Timestamp: 2020-04-16 08:05:19Z

**Additional context**

**Please note: Do not include sensitive information like PII, OII, credentials, secrets, and tokens.**

For **privacy/security** issues please see instructions [here](https://github.com/AzureAD/microsoft-authentication-library-for-android#security-reporting)

**Comment by shahzaibj** [comment]
Hi @Rajashekhargouda It seems that you are using a pre-release version (0.2.2) of MSAL. Please upgrade MSAL to the latest version v1.5.0 https://github.com/AzureAD/microsoft-authentication-library-for-android/releases  

I am going to close the issue for now, feel free to reopen if the issue persists after upgrading MSAL to the latest version.

**Comment by iambmelt** [comment]
As an additional piece of info, @Rajashekhargouda 

This error indicates that your refresh token has expired; to acquire a new token you can call `acquireToken()` and complete an interactive request. Once you have a new refresh token, you can continue to call `acquireTokenSilent()` until that token expires or is revoked

I will call out, this refreshToken seems to be _very_ short lived (~1 day) -- unless this short lifetime is intentional, you may want to extend it as part of your B2C/IEF journey spec otherwise your users will be prompted to reauthenticate daily:
- Grant issued time: 1586869378 (GMT Tuesday, April 14, 2020 1:02:58 PM)
- Grant expiration time: 1586955778 (GMT Wednesday, April 15, 2020 1:02:58 PM)

**Comment by Rajashekhargouda** [comment]
Thank you @iambmelt  and @shahzaibj for the feedback. I wud upgrade to the mentioned version and try
