### ISSUE TITLE
IPublicClientApplication acquireToken takes a String[] for list of scopes while other APIs use List<String>

### ISSUE THREAD

**Issue by joshfriend** [AzureAD/microsoft-authentication-library-for-android#1058]
**Is your feature request related to a problem? Please describe.**
Most APIs receive a `List<String>` for the oauth scopes, but `IPublicClientApplication.acquireToken` still uses the old `String[]`.

**Describe the solution you'd like**
Please make this consistent with other APIs that use `List<String>`

**Comment by shahzaibj** [comment]
Hi @joshfriend the other APIs you are referring to, are those the ones that accept `AcquireTokenParameters`?

**Comment by joshfriend** [comment]
Yes, any method that accepts a subclass of `TokenParameters` basically.

I noticed that `void acquireToken(Activity, String[], AuthenticationCallback)` uses `Arrays.asList` internally since everything else uses `List<String>` and thought it was odd.

Also, that version of `SingleAccountPublicClientApplication.acquireToken` throws `com.microsoft.identity.client.exception.MsalClientException: There is no signed in account.` to the callback, but the one that accepts `AcquireTokenParameters` does not. The docs for both method versions are identical

**Comment by joshfriend** [comment]
Aha! I think I understand my last half of that comment. #767 added checks for incorrect api use, but missed the `acquireToken(AcquireTokenParams)` version. I need to be using `signIn()` instead, would be nice if the exception or docs had a message saying as much.

I might make a PR for that...

**Comment by shahzaibj** [comment]
@joshfriend Agreed. We have an open github issue for the single account issue here: https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/1032

We are actively working on improving the experience in that area.

For the first issue around difference in the data type of `scope` parameter, I agree with you, and we need to offer the same experience, however, since this public API and people may be using it already, we can't alter the API itself. We can add an additional overload as follows:

`void acquireToken(Activity, List<String>, AuthenticationCallback)`

**Comment by joshfriend** [comment]
I would just deprecate the methods that dont use `*Params` builder classes rather than add more of the individual parameter methods just to address this consistency issue, but you would know better than I if there were reasons for keeping the non `*Params` class ones.

**Comment by shahzaibj** [comment]
Thanks for the feedback @joshfriend, I'll discuss with the team and get back to you.
