### ISSUE TITLE
Fetch Broker App Information with MSAL

### ISSUE THREAD

**Issue by ghost** [AzureAD/microsoft-authentication-library-for-android#1139]
We are trying to fetch broker app name and version that is used for MSAL authentication.

We have included following piece of code in configuration json file.

```
"telemetry": {
    "notify_on_failure_only": false
  }

```
We are tried using `Telemetry.addObserver(ITelemetryDefaultObserver)`, but the observer is not being notified about broker app changes.

Would you please let me know, what is the way I can fetch broker app name and version using MSAL android java SDK or if I am missing something in the current implementation?

Thanks in advance!

**Comment by shahzaibj** [comment]
Hi @nishidoshi We do not notify of broker app changes either via Telemetry or via some API. Can you tell me more about your scenario and why you might need an API exposing broker app information?

**Comment by nishidoshi** [comment]
Hey @shahzaibj 

We are sending diagnostics log for errors or failures while authentication. In those logs we specify broker app name and version as sometimes, the authentication fails because of an older version of broker app.

We recently migrated our codebase from ADAL to MSAL. In case of ADAL we were able to fetch two values : broker app name and version. Hence, solve errors and issues in authentication, we are trying to find a similar API in MSAL.

Thanks!

**Comment by nishidoshi** [comment]
Hey @shahzaibj ,

Any updates on the issue raised? Can the broker app info be made available with next release if that's possible?

Thanks.

**Comment by nishi1612** [comment]
Hey @shahzaibj ,

Any updates about rolling out the feature in a subsequent release?

Thanks

**Comment by shahzaibj** [comment]
@nishi1612 We will discuss within the team about rolling out such a feature and get back to you with an update. Thanks!

**Comment by nishi1612** [comment]
Hey @shahzaibj ,

Any updates on shipping of this feature?

Thanks
