### ISSUE TITLE
Changing the timeout config programatically

### ISSUE THREAD

**Issue by 4gus71n** [AzureAD/microsoft-authentication-library-for-android#1168]
Hello :wave:!

**Context**

So, I'm in a scenario where I need to programmatically change the MSAL timeout values. My app can go through a lock screen if a time threshold is reached, and the user has to authenticate himself via biometrics to unlock this screen and continue using the app. However, I do also check against MSAL to see if the user session is valid - whether I'm able to fetch an access token through the MSAL library - and sometimes the MSAL library may go to the server to fetch a new fresh access token, if this ever happens I want to set a shorter timeout so the user isn't waiting for more than 3 seconds in this lock screen.

**What I tried**

I think that the only available API to set the timeout is via the `singlePublicClientApplication.configuration.httpConfiguration.setConnectTimeout` I've tried with this API but it doesn't look like it changes anything. The full code is like this:

```

	// Save the original timeout values on these variables
	val legacyConnectTimeout = singlePublicClient.configuration.httpConfiguration.connectTimeout
	val legacyReadTimeout = singlePublicClient.configuration.httpConfiguration.readTimeout
	singlePublicClient.apply {
		// Programatically change the timeout to three seconds
		configuration.httpConfiguration.apply {
			connectTimeout = 3000
			readTimeout = 3000
		}
	}.acquireTokenSilentAsync(
		AcquireTokenSilentParameters.Builder()
			.fromAuthority(singlePublicClient.configuration.defaultAuthority.authorityURL.toString())
			.forAccount(activeAccount)
			.withScopes(scope)
			.forceRefresh(forceRefresh ?: sharedPreferencesUseCase.devForceRefresh)
			.withCallback(
				object : SilentAuthenticationCallback {
					override fun onSuccess(authenticationResult: IAuthenticationResult?) {
						// We restore the original timeouts right after sending the req.
						singlePublicClient.apply {
							configuration.httpConfiguration.apply {
								connectTimeout = legacyConnectTimeout
								readTimeout = legacyReadTimeout
							}
						}
						// ... Continue 
					}
					override fun onError(e: MsalException) {
						// We restore the original timeouts right after sending the req.
						singlePublicClient.apply {
							configuration.httpConfiguration.apply {
								connectTimeout = legacyConnectTimeout
								readTimeout = legacyReadTimeout
							}
						}
						// ... Continue 
					}
				}
			)
			.build()
	)
```

You can see that (1) I store the original timeout values on some variables to roll them back later (2) I change the timeout values to 3 seconds (3) I fetch a new token via the `acquireTokenSilentAsync` and you can see that I've code there to force the MSAL library to fetch a token from the server via the `forceRefresh(Boolean)` option.

However, when I test this, I throttle my connectivity, and I have to wait for 10 seconds until the requests times out. I'm using the `1.5.1` version of the lib, I did try to update to the latest `2.0.1` version and see if something changed, but I still see the same behavior.

_Am I using the right API? Is it possible to programatically change the MSAL timeout values on the fly?_ I've seen some PRs that got merged about a `MsalSettings` class which is able to set the timeout values, but I don't see that class available.

Thanks, appreciate all the help that you guys provide! :bow:

**Comment by iambmelt** [comment]
Hi @4gus71n 

Our programming model intends for these values to be configured during development such that they can be loaded from your [application's configuration](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-configuration#http) and be loaded [once](https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/dev/msal/src/main/java/com/microsoft/identity/client/PublicClientApplication.java#L1077-L1101).

That said -- this can be circumvented by accessing some static fields in our HTTP stack [here](https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/dev/msal/src/main/java/com/microsoft/identity/client/PublicClientApplication.java#L1095) and [here](https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/dev/msal/src/main/java/com/microsoft/identity/client/PublicClientApplication.java#L1099).

A few words of caution and an alternative suggestion...

Caution
- Because you're accessing internal fields which _are not_ considered part of our public API, these may move, be renamed, or otherwise change behavior in future releases.
- As you can see from looking at the HTTP internals: the read/connect timeouts are read as global-state configuration, and aren't _really_ configurable on a per-request basis; not in an enforceable way, anyway.
- In general, any class with [`internal`](https://github.com/AzureAD/microsoft-authentication-library-common-for-android/blob/dev/common/src/main/java/com/microsoft/identity/common/internal/net/HttpRequest.java#L23) in its package name is not considered to be part of our public api
- If your app supports brokered auth, these timeouts will be ignored -- this cannot be overridden
- Controlling UX with HTTP timeouts may have unintended effects
    * MSAL makes requests other than `/token` requests, including loading cloud configuration metadata and in the case of B2C policy metadata as well. These values will be cumulative, so if we have to make two requests, a 10 second read/connect timeout could potentially be as long as 40 seconds (2x10s CONNECT + 2x10s READ) -- **this is almost certainly not your intent**.

Alternative suggestion
- Consider using something like a [`CoundownLatch`](https://developer.android.com/reference/java/util/concurrent/CountDownLatch#await(long,%20java.util.concurrent.TimeUnit)), [`Handler`](https://developer.android.com/reference/android/os/Handler#postDelayed(java.lang.Runnable,%20java.lang.Object,%20long)) or other mechanism to explicitly gate your app's transition, rather than a network timeout which may be more unpredictable
