### ISSUE TITLE
Is it possible to authenticate websites with a broker like the MS-Authenticator-App on android?

### ISSUE THREAD

**Issue by meinto** [AzureAD/microsoft-authentication-library-for-android#1190]
**Is your feature request related to a problem? Please describe.**

Like described in https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2395 my use case is, that we use the MS-Authenticator app on android in shared-mode to provide SSO for different users. The problem is, that we also have SPAs on the same device which should also use the authentication mechanism with the MS-Authenticator app, to provide SSO across native apps and SPAs. Is there a way to achieve this?

**Describe the solution you'd like**

Like described above the suggested behavior would be, that native and web-apps use the MS-Authenticator app in shared mode to provide SSO across native and web-apps.

**Comment by SaeedAkhter-MSFT** [comment]
I not sure there's a way to satisfy this scenario on Android due to limitations of the operating system.

For devices that are in "shared-mode" it is the responsibility of the application to subscribe to account change notification and then clear state after "onAccountChanged" (see https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-android-shared-devices#shared-device-sign-out-and-the-overall-app-lifecycle).  The problem with a website is that there is no way in Android that I'm aware of that would allow us to: (1) to have a website invoke the Authenticator app during sign-in and (2) receive notifications from the Authenticator app "on account change".  Therefore, when you tap "Global Sign-out" it would sign out of your Android applications that support shared device mode and sign out of Microsoft Teams, but it would not sign you out of that website.  There would also be no way to clear any state that might be cached via JavaScript or open and visible in the browser.  The next employee to pickup the device would gain access to data they should not have access to.

The best idea I can offer is to turn your website into a native Android application (which is obviously a lot of work on your side).

**Comment by Om83** [comment]
1.	We can't SSO for SPA or web apps today because Broker still uses embedded Browser. In future our plan is to move Broker to system browser.  Alternatively, Edge likely will also be FLW compliant in future and can support such SSO needs without the system browser change for Broker. However there are no fixed timelines are known for these changes today.
2.	We do trigger a sign out today in default browser when an FLW app invokes sign out. This is done by invoking  https://login.microsoftonline.com/common/oauth2/v2.0/logout ’ on the default browser and this is a best attempt to remind user to sign out of his account in browser.
