### ISSUE TITLE
Login is crashing when using androidx.browser:browser:1.2.0

### ISSUE THREAD

**Issue by timfreiheit** [AzureAD/microsoft-authentication-library-for-android#1197]
The Microsoft-Authentication-Library depends indirectly on `androidx.localbroadcastmanager:localbroadcastmanager:1.0.0` by including `androidx.browser:browser:1.0.0`. 
This transitive dependency was removed in version `androidx.browser:browser:1.2.0` which results in a crash when trying to login.

The `LocalBroadcastManger` is for example used in the [CommandDispatcher.java](https://github.com/AzureAD/microsoft-authentication-library-common-for-android/blob/4fe161b87b7d98bdd7a4f5bcc604cf839979c6dd/common/src/main/java/com/microsoft/identity/common/internal/controllers/CommandDispatcher.java)

A possible fix is to include the dependency separately using:

```gradle
implementation("androidx.localbroadcastmanager:localbroadcastmanager:1.0.0")
```

**Comment by iambmelt** [comment]
Removing the bug tag as this isn't an MSAL issue, but a dependency version consideration by apps taking MSAL.

**Comment by iambmelt** [comment]
Took a look at this - unfortunately MSAL cannot yet update to `androidx.browser:1.2.+` due to a lack of J8 bytecode support in our build pipeline. Support for this will show up eventually, but we don't have it today. Once we have it we will update the version of `androidx.browser` to a newer version at which point we will have to add the `androidx.localbroadcastmanager` dependency explicitly. As this isn't our current ship-state, this isn't urgent or required.

So, in the meantime I'm going to suggest the following: if you are an app that wants to take `androidx.browser` at `1.2.0` or higher you can [exclude this transitive dependency from MSAL](https://docs.gradle.org/current/userguide/dependency_downgrade_and_exclude.html) and [enable J8 support in your project](https://developer.android.com/studio/write/java8-support#library-desugaring) via your consuming application's `build.gradle` until such time as MSAL fully supports J8 compilation.
