### ISSUE TITLE
Set the login hint for signInAgain function

### ISSUE THREAD

**Issue by combatistor** [AzureAD/microsoft-authentication-library-for-android#1273]
**Describe the bug**
Actually I'm not sure if this is a bug, or more a feature request.
I'm using SinglePublicClientApplication to login users in the app through azure B2C Sign in recommended user flow using email as Identity provider. 
After the token is expired I use signInAgain function, but because I'm using B2C, I can't get "username", "email" or "upn" from the token response, in this case I get the email field with the login hint set to:  "Missing from the token response".

I already checked the issue #1117, and they are getting the expected behaviour (in the gif) though they might be using azure AD, not B2C like me.

Is there a way at least to set the login hint if the username is missing from the token?

**Smartphone:**
 - Device: Nexus 5X
 - Android Version: 8.1.0
 - Browser: Chrome
 - MSAL Version: 2.0.5

**Stacktrace**
No stacktrace.

**Expected behavior**
This is the expected behaviour:
<img src="https://user-images.githubusercontent.com/990063/89074621-81a2a680-d331-11ea-8134-b9d42ecd6008.gif" width="300">

**Actual Behavior**
My behaviour
<img src="https://user-images.githubusercontent.com/6489301/104310633-5c88a580-5517-11eb-88d4-a9ffc217eb9b.jpg" width="300">

**Comment by iambmelt** [comment]
Hi @combatistor 

>I'm using SinglePublicClientApplication to login users in the app through azure B2C

Uh oh! This is not supported; please have a read of our documentation [here](https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/dev/docs/publicclientapplication.md#introduction) and [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-android-b2c#configure-known-authorities-and-redirect-uri). Because B2C policies are modeled as separate authorities (and separate authorities issue separate tokens/accounts) B2C apps are _by definition_ MultiAccount apps. Using a SingleAccount app to implement B2C will cause hard-to-reproduce bugs related to token claims and result in cache misses when trying to perform silent auth. You will need to change your implementation to use a MultiAccountPublicClientApplication to ensure a bug-free experience

>Is there a way at least to set the login hint if the username is missing from the token?

You will need to configure the B2C policy to return a `preferred_username` claim; guidance on how to do this (or where to source this claim data) is bit beyond the scope of project, I would suggest reviewing the[ B2C policy documentation](https://docs.microsoft.com/en-us/azure/active-directory-b2c/tokens-overview#claims) to get familiar with editing policies and their emitted tokens/claims

**Comment by combatistor** [comment]
Thank you for the clear reply.

I switched back to MultiAccount using msal android sample code, now at least I can customize login hint with something when renewing the token. 

Regarding B2C policy I think it is not possible at the moment to get `upn` or `preferred_username` but this might be a B2C limitation.
