### ISSUE TITLE
Remove account api is not removing the account from Authenticator app or not even signout

### ISSUE THREAD

**Issue by vramasam** [AzureAD/microsoft-authentication-library-for-android#1301]
**Describe the bug**
Development issue. 
STEP 1: Using create PublicClientApplication created the application with the clientID, redierct uri and other details
STEP 2: Using getAccount publicClientApplication, able to get the account
STEP 3: Pass the account information to the removeAccount api. Call back of removeAccount api is success (onRemoved gets called). 

But the account is still present in the broker app. And also next time when we login using broker app, it shows the authenticator selector screen with the account we removed using removeAccount, and also its not asking for the password, on tap of the user, its login directly.

So here trying to understand, what is the function of this removeAccount api present in the **MultipleAccountPublicClientApplication class
public void removeAccount(@Nullable IAccount account, @NonNull RemoveAccountCallback callback) {
        this.removeAccountInternal(account, callback, "930");
    }**  

**Smartphone (please complete the following information):**
 - Device: All Device
 - Android Version: All OS version
 - Browser Using Autehnticator(Broker) App
 - MSAL Version 2.0.4

**Stacktrace**
If a crash occurs, include the stacktrace.

**To Reproduce**
Used Remove account api of MSAL
    publicClientApplication.removeAccount(account,
        new IMultipleAccountPublicClientApplication.RemoveAccountCallback()
        {
                @Override
                 public void onRemoved()
                 {
                                                
                 }

                 @Override
                 public void onError(@NonNull MsalException e)
                 {
                                                
                  }
               });

onRemoved callback gets called but the account is still present in the Broker app. And also it's not asking for the password, it's getting login directly with out asking for password.

STEP 1: Using create PublicClientApplication created the application with the clientID, redierct uri and other details
STEP 2: Using getAccount publicClientApplication, able to get the account
STEP 3: Pass the account information to the removeAccount api. Call back of removeAccount api is success (onRemoved gets called). 

But the account is still present in the broker app. And also next time when we login, its not asking for the password, its authenticator select account screen, on tap of the user, its login directly

**Expected behavior**
Here Expectation, on remove account, it should remove the account from the broker app. At-least it should ask for password.

**Actual Behavior**
On removing account, account should get removed from Authenticator app. At-least it should ask for password on signin.

**Screenshots**

**Additional context**

**Please note: Do not include sensitive information like PII, OII, credentials, secrets, and tokens.**

For **privacy/security** issues please see instructions [here](https://github.com/AzureAD/microsoft-authentication-library-for-android#security-reporting)

**Comment by iambmelt** [comment]
I received an internal email message about this GitHub issue and have responded there; leaving this issue open.

**Comment by vramasam** [comment]
We have any update here. Ideally using "MultipleAccountPublicClientApplication" how to do sign-out. Please give the preferred way of sign-out.

**Comment by iambmelt** [comment]
Seems my answer from the other thread never made it to you: reposting here.

----

I can take a shot at filling in some of the gaps here; at a glance, this looks to be expected behavior.

First, I’ll direct your attention towards this documentation concerning the expected behavior of removeAccount APIs – see the class summary.

(screengrab of doc below)
 
![image](https://user-images.githubusercontent.com/990063/108268839-f7c9f780-7121-11eb-9f6e-f29a9f1cc98a.png)

In simplified terms, this means that if an account is added to the broker (for example, via workplace join) it will not be removed because it is in use by the broker app and accordingly, may be in-use by other apps as well. MSAL’s removeAccount() API does not behave like global signout. It does not remove the account from the device and, if the account added to the broker has been used to acquire a PRT, that PRT can be used to authenticate an account for an app so long as the PRT remains on the device. This is why the account continues to be available in the ‘Select Account’ menu when interactively authenticating via the app.

So… how do we force the user to reauthenticate if the account has not been removed the broker? The answer is via the [prompt parameter](https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/dev/docs/prompt_behavior.md#android-prompt--promptbehavior) – in this case, you would want to supply ‘LOGIN’, such that user is force to supply credentials. 

If you are interested in implementing behavior such as ‘global signout’ please refer to our documentation on [SingleAccountMode & Shared Device Mode](https://docs.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-shared-device-mode#:~:text=Shared-device%20mode%20allows%20you,and%20access%20customer%20information%20quickly). These modes will allow you add/remove a user from the context of a device, rather than the context of an application – note that Shared Device Mode must be enabled in the Broker for these device-signout/removeAccount behaviors to take effect.

Hope this helps,
Brian

**Comment by vramasam** [comment]
@iambmelt  Thank you for the clear explanation on Authenticator approach 

In case of Non-broker(Without Authenticator) approach ( "broker_redirect_uri_registered" false and "authorization_user_agent" DEFAULT. ), then app will use the custom tab/browser approach.

During this case , what is the appropriate sign-out approach we can follow for "MultipleAccountPublicClientApplication"? Can you please explain this as well?

**Comment by iambmelt** [comment]
> @iambmelt Thank you for the clear explanation on Authenticator approach
> 
> In case of Non-broker(Without Authenticator) approach ( "broker_redirect_uri_registered" false and "authorization_user_agent" DEFAULT. ), then app will use the custom tab/browser approach.
> 
> During this case , what is the appropriate sign-out approach we can follow for "MultipleAccountPublicClientApplication"? Can you please explain this as well?

Sure @vramasam -- calling `removeAccount()` will remove the tokens from the _local cache_ in the absence of the broker. If you also wish to remove SSO state (ie cookies) from the user's Browser you will need to navigate to the AAD `end_session_endpoint`. Alternatively, if you are using the WebView, you can [clear the WebView's cookies](https://developer.android.com/reference/android/webkit/CookieManager#removeAllCookies(android.webkit.ValueCallback%3Cjava.lang.Boolean%3E)).

You can discover the `end_session_endpoint` from [this OpenID-Config Metadata](https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration) --  at the time of this writing, the value is: `https://login.microsoftonline.com/common/oauth2/v2.0/logout`

**Comment by vramasam** [comment]
Thank you @iambmelt for all the inputs.

**Comment by vramasam** [comment]
Hello @iambmelt 

We are having one query on SSO in Android

We have 4 different apps in Android. Each app is having its own redirect URI.

For better understanding giving the below scenario:
Step 1:  From "X1" app , I am doing interactive login. On Interactive login success in Authentication result got the account information and we store the "Identifiaction User" info authenticationResult.getAccount().getId() and also authenticationResult.getAccount().getUsername() in the local Database.

Step 2: From "X2" app, I am trying to call ""publicClientApplication.getAccount()" with the stored "Identification User" , I am getting account as null.

Is this expected behaviour? Our expectation, if we pass the stored "Identification User" or "Logint Hint" and call the getAccount api we should get the account information , so that we will call "acquireTokenSilentAsync" with the fetched account information across apps.

Note: If we calls the "publicClientApplication.getAccount" with in X1 app, it's able to find the account and silent api got success.

In IOS we saw something like this here to support this: https://github.com/AzureAD/microsoft-authentication-library-for-objc

Add a new keychain group to your project Capabilities. Keychain group should be com.microsoft.adalcache on iOS and com.microsoft.identity.universalstorage on macOS.

Kindly, Can you please give your valuable inputs here.

**Comment by iambmelt** [comment]
Hi @vramasam -- This sounds expected. There is no "silent SSO" across 3rd party apps with MSAL. Please see this documentation for more information on these scenarios:

https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-android-single-sign-on

**Comment by vramasam** [comment]
@iambmelt  Thank you so much for the quick reply

In that case if there is no "silent SSO" across apps, if we can pass the  "Login Hint" to the interactive login with out any Prompt, will authenticator able to get the token without any "Authenticator selector and password" screen, to achieve the SSO functionality works across the apps?

Can you please confirm, will the above approach is proper?

**Comment by iambmelt** [comment]
@vramasam 

>if we can pass the "Login Hint" to the interactive login with out any Prompt, will authenticator able to get the token without any "Authenticator selector and password" screen, to achieve the SSO functionality works across the apps?

This is not supported _by design_, otherwise applications that a user has not consented to would be able to request tokens on behalf of a user. Requesting tokens on behalf of a user requires authorization/authentication and granting consent to the requested OAuth scopes. Therefore, the expectation is that any 3rd party (non-msft) app which is requesting tokens on behalf of a user _must_ perform their first auth call interactively.

To avoid a password prompt, consider using [CustomTabs/Browser based auth](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-android-single-sign-on#authorization-agents): if the user has an active session (cookie) in the browser already, they may be able to skip entering a password when authorizing a new app, depending on the Conditional Access requirements of the requested resource and tenant

**Comment by vramasam** [comment]
@iambmelt 
My observation from PoC is below:

Authenticator based:
1. From "App1" I am doing interactive login (Giving username and password), stored the "LoginHint"(Ex: xxx.onmicrosoft.com) information in the local DB.
2. From "App2",  I am doing interactive login by passing the stored "LoginHint"(with xxx.onmicrosoft.com), I am able to sign-in successfully without username and password (Because the account exist in the authenticator app), it was able to get the token successfully.

Browser based:
1. From "App1" I am doing interactive login (Giving username and password), stored the "LoginHint"(Ex: xxx.onmicrosoft.com) information in the local DB.
2. From "App2",  I am doing interactive login by passing the stored "LoginHint"(with xxx.onmicrosoft.com), I am able to sigin-in successfully without username and password (Because the account exist in the browser/chrome custom tab).

I am observing the above behaviour, which we are expecting also. Hope our design is fine to achieve the SSO across apps for first time.
