### ISSUE TITLE
WebView - Skype behaviour

### ISSUE THREAD

**Issue by AndaBucsa** [AzureAD/microsoft-authentication-library-for-android#1439]
Hello,

I am in the process of adding "Login with microsoft"  functionality and I would like to implement the same behaviour as Skype. I attached also a gif of how Skype is  behaving.

I already read the official documentation (https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-android-single-sign-on#webview) and I couldn't find any guidance related to customising the WebView or the transition between sign in button and WebView. The only thing that it is mentioned is the "However, WebView does provide the capability to customise the look and feel for sign-in UI. See Android WebViews for more about how to do this customisation." but nothing related to how the custom webview will be used by MSAL.

Could you please advise me if this is possible and if it is how can I achieve the needed behaviour?

Thank you,
Anda

![Skype-Login](https://user-images.githubusercontent.com/11571966/122216668-4f505800-ceb5-11eb-91ee-76ed57cece72.gif)

**Comment by shahzaibj** [comment]
@AndaBucsa Thanks for reaching out. The following statement is a bit misleading:

> However, WebView does provide the capability to customise the look and feel for sign-in UI. See Android WebViews for more about how to do this customisation.

It is misleading because I believe what this really means is it allows us as MSAL maintainers to customize the webview, however, our consumers that use MSAL can only customize it as much as we let them. @hamiltonha we should improve that documentation to be more explicit about what is supported for customization vs not in our MSAL webview.

Currently we only support configuring whether the zoom should be allowed inside the webview and whether zoom controls should be visible or not. You can configure this via the [msal configuration file](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-configuration). Here's an example: https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/dev/msal/src/main/res/raw/msal_default_config.json#L15-L16

Customizing the spinner and/or other things is currently not supported.
