### ISSUE TITLE
Unable to complete authorization as there is no interactive call in progress. This can be due to closing the app while the authorization in process.

### ISSUE THREAD

**Issue by educosta** [AzureAD/microsoft-authentication-library-for-android#1562]
It gives below error when go to login page. I can't use webview because I have social login

**Unable to complete authorization as there is no interactive call in progress. This can be due to closing the app while the authorization in process.**

![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/3913187/143867321-f79fcdda-6141-484d-a6ea-2cd68f2efbc9.png)

**Comment by wainaina** [comment]
This is due to closing the app while the authorization is in progress. The flow requires that the browser/webview be opened, for authorization and then revert control back to the calling thread..

**Comment by manish-etymon** [comment]
We are facing same issue. we are using: ` "authorization_user_agent": "BROWSER"`, can we use  "authorization_user_agent": "WEBVIEW"? looks like that is not having issue. but does "WebView" have any issue? any drawback?

**Comment by MarceloEsser** [comment]
> We are facing same issue. we are using: ` "authorization_user_agent": "BROWSER"`, can we use "authorization_user_agent": "WEBVIEW"? looks like that is not having issue. but does "WebView" have any issue? any drawback?

The issue with webview is that you cannot use social media interactions, you can't sigin your users using iCloud, Google, Facebook or any other social media.

This error occurs because the android basically kill the "login process" in background and the browser lost de application so it can't back to the app with de sigin result. 
With webview this error shouldn't happen just because the application don't go to the background.
Our workaround to this error was adding a new button on our login screen, like "need help to sigin?", this button open a webview to the user AND we inform the users that they can't use social media on this login version.
![image](https://github.com/AzureAD/microsoft-authentication-library-for-android/assets/28572176/5ff2d4a0-bcfc-4c9a-9135-3c2f468be26e)

**Comment by kientrant1** [comment]
Switching authorization_user_agent to "WEBVIEW", the UI looks like different to Browser mode. It doesn't have close (x) button to cancel popup screen.
Do we have any other idea to resolve this one? I'm checking with Android 11. Seems like it happens on some device - not all.
