### ISSUE TITLE
AcquireTokenSilently took fairly long time to retrieve access token from cache

### ISSUE THREAD

**Issue by iori57** [AzureAD/microsoft-authentication-library-for-android#1607]
Following the guidelines highlighted at https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-acquire-cache-tokens , every time before I make an API call I'll first call acquireTokenSilentAsync to get the access token either from cache, or a new one automatically using the refresh token.

This works well, except that it seems to be quite slow in retrieving from cache. See below screenshot for timing:

![image](https://user-images.githubusercontent.com/5056279/159799787-2a27dd0b-5f2f-4d1c-b285-730b0e8431ce.png)

As you can see when I just started the app, it manage to retrieve the access token used in the last run (I copied it out to a text file and compared) it took 2 seconds. Subsequently it became faster on each run, but it still take more than half a second to retrieve the exact same access token from cache. Loading from cache should take just about 5ms to 10ms?

This is my acquireTokenSilently implementation, just basic configuration.
```
private fun acquireTokenSilently(serviceName: String, callback: IAcquireTokenSilentlyCallback) {
        val parameters: AcquireTokenSilentParameters = AcquireTokenSilentParameters.Builder()
            .withScopes(authConfigReader.getServiceScopes(serviceName))
            .forAccount(firstAccount)
            .fromAuthority(authConfigReader.authorityUrl)
            .withCallback(object : SilentAuthenticationCallback {
                override fun onSuccess(authenticationResult: IAuthenticationResult) {
                    callback.onSuccess(authenticationResult.authorizationHeader)
                }

                override fun onError(exception: MsalException) {
                    callback.onError(mapMsalException(exception))
                }
            })
            .build()

        publicClientApp!!.acquireTokenSilentAsync(parameters)
    }
``` 

Do we need to write our own token persistence implementation like the one mentioned in the MSAL for Java section? This is not mentioned in the MSAL for Android section though:
https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-java-token-cache-serialization

Thanks!
Bruce

**Comment by slowcar** [comment]
I implemented a small cache in our application to circumvent this issue, a simple hashmap with the msalAccountId as key and the token with an expiresOn date as value. Retrieving the cached token checks the expiresOn value against the current timestamp.
In case of an authorization error the cache entry is discarded and a fresh token requested from the library.

**Comment by wainaina** [comment]
The extra verification step occurs while performing cloud discovery.

Before any :acquireTokenSilent call the broker service has to check whether the Azure Active Directory Service is initialized or not, if not, we start by initializing the AAD service and this requires a HTTP call to the service. We validate the cloud we are using at that point in order for us to verify that the clients are only getting responses from pre-verified sources (during cloud discovery).

Considering the token in the token in the cache may have expired in the first call, we then have to make an extra call to AAD, acquire the token then persist the token.

During this process, the HTTP stack warm up adds to the time taken during the first call.

Subsequent calls end up being faster because:

 - Once AAD is initialized, we do not perform cloud discovery again,
 - HTTP stack is already warmed up and should any call be made, it's a lot faster.
 - Once we have current tokens in the cache and AAD is initialized, the extra checks do not lead to any HTTP calls making the calls have a near constant time.
