### ISSUE TITLE
Allow multiple Apps to use same redirect URI

### ISSUE THREAD

**Issue by dcannaWegmans** [AzureAD/microsoft-authentication-library-for-android#1623]
The latest version of the library (3.0.2) throws an exception if you have multiple apps listening to the same redirect URI. Our company tests with multiple flavors of the android app and requires us to be in this situation. Can you add some sort of override feature that will allow this to happen like it did in version 2.2.3 and before?

Thank You!

**Comment by MathieuCalba** [comment]
We are facing the same issue. can we have more information about why this change has been made?

**Comment by negoe** [comment]
@dcannaWegmans @MathieuCalba We intentionally don't support this scenario because Android OS, when it returns the authorization code on completion of authorization; the redirect uri should be unique to access the correct application it is associated with. Otherwise, Android OS will present a prompt to the user asking them to select an app out of the multiple apps using the same redirect uri, which will be confusing to end user.

**Comment by wegdev** [comment]
Understood, but it is fairly common for android development to have different flavors of the same application running on a single device, where production user's will not ever see that. We have been working with that 'confusion' for years and it has worked out fine. Is there any way to get this to be a configurable value instead of enforcing us to only have 1 version of our application per device?
