### ISSUE TITLE
Play Store Error: Unsafe Cipher mode in classes of MSAL library latest version

### ISSUE THREAD

**Issue by swetasamasti2310** [AzureAD/microsoft-authentication-library-for-android#1659]
There is an error showing on play store for our app as follows:
Unsafe Cipher Mode
Your app contains a less secure encryption mode.
com.microsoft.identity.common.adal.internal.cache.StorageHelper.getKeyThumbPrint

**Comment by negoe** [comment]
@swetasamasti2310 Can you please confirm which version of ADAL are you using?

**Comment by swetasamasti2310** [comment]
> @swetasamasti2310 Can you please confirm which version of ADAL are you using?

We are using MSAL 3.0.2 (latest). But we observed this issue also with 2.2.1.

**Comment by drachim-dev** [comment]
I have encountered the same problem. It seems that the problem should have been solved in #1540

**Comment by dmoodz** [comment]
Can anyone confirm if this is fixed in any specific version? I'm using an npm package named @recognizebv/capacitor-plugin-msauth via Ionic and am getting this message. I can see an Android dependency for this package and it's using v2.2.0. It looks like the related issue #1540 solved it in 2.2.3, but above @swetasamasti2310 mentioned it broken again in 3.0.2.

**Comment by opt05** [comment]
> Can anyone confirm if this is fixed in any specific version? I'm using an npm package named @recognizebv/capacitor-plugin-msauth via Ionic and am getting this message. I can see an Android dependency for this package and it's using v2.2.0. It looks like the related issue #1540 solved it in 2.2.3, but above @swetasamasti2310 mentioned it broken again in 3.0.2.

On the latest 4.2.0 deployed in the Play Store and we no longer have this warning
