### ISSUE TITLE
Device suddenly displaying "Invalid username or password"

### ISSUE THREAD

**Issue by Halfpint-Code** [AzureAD/microsoft-authentication-library-for-android#1660]
We have a client that is experiencing the inability to login since last week (of 7/11/22) on their Zebra TC8000s. But only 3 of their devices went down. They are able to log in to the same app, we provide, on their personal phones. It's not hitting any of our breakpoints in Android Studio past the initial acquireToken(parameters) call.

When we input any credentials into the problem device, they all come up "Invalid username or password".

We have tried a factory reset of the problem device I got from them and this does not help.

This is working on the same model Zebra TC8000 device that we currently have in-house for development.

Could there be any code issue in the MSAL framework that might be causing this. I suspect something happened to the device but don't know enough about the hardware to determine that. I will likely be deferring this to the client's IT.

AcquireTokenParameters parameters = new AcquireTokenParameters.Builder()
                    .startAuthorizationFromActivity(LoginActivity.this)
                    .fromAuthority(B2CConfiguration.getAuthorityFromPolicyName(B2CConfiguration.EMAIL_SIGNIN_POLICY))
                    .withScopes(B2CConfiguration.getScopes())
                    .withPrompt(Prompt.LOGIN)
                    .withAuthorizationQueryStringParameters(B2CConfiguration.getExtraQueryParameters())
                    .withCallback(getB2CAuthenticateCallback())
                    .build();
mAuthContext.acquireToken(parameters);

**Comment by negoe** [comment]
@Halfpint-Code Based on the information you have provided, it appears that the issue is specific to the problem devices the client is experiencing, as the same app works on their personal phones and on the same model of device you have in-house for development.
It is possible that there may be a hardware issue with the devices themselves, or that the issue is related to their network configuration or device settings. Given that the issue is only affecting a few devices and is not hitting any breakpoints in Android Studio, it is unlikely that there is a coding issue with the MSAL framework.
