### ISSUE TITLE
authorization_user_agent stuck at webview with no way to clear it

### ISSUE THREAD

**Issue by hansheng654** [AzureAD/microsoft-authentication-library-for-android#1734]
**Describe the bug**
Enterprise Live Production App,  I pushed a version with authorization_user_agent set to webview, then we started to facing authentication issues for unknown reasons. Then I decided to revert to the **default** which is **browser** authentication .
However, this does not change it back to browser auth, so I tried to change from **defualt** to **browser** hoping it can force the agent to be using browser again. No luck.
I tried uninstall the app, delete accounts in Settings, restarting the phone, no luck, it always go to webview for auth which is causing problem.

I tried to change the Application ID to something else, suddenly it recognise the browser agent config and start auth through browser. when i change it back to the original one, it goes back to webview agent.  

It seems there is a mapping somewhere that maps Application ID to how you auth, can someone please advice how to clear this or prehaps fix this bug?

**Smartphone (please complete the following information):**
 - Device: Sumsang S22 Ultra
 - Android Version: recreated both at 12 and 13
 - Browser : Chrome
 - MSAL Version , tried +3.0.0, 4.1.0 and 4.0.5, issue present in all those versions

**Stacktrace**
If a crash occurs, include the stacktrace.

**To Reproduce**
1. Sumsang phone ( i know it can sometime cause problems due to sumsang's own built)
2. change authorization_user_agent to be webview
3. deploy and run
4. change authorization_user_agent to be default
5. if you are unlucky or from some unknown reason, it will stuck at webview. I have tested in different varient, the issue seems inconsitent
6. change authorization_user_agent to be browser
7. deploy and run - notice it still stuck at webview

If related to development, please provide relevant configuration details necessary to understand your problem including any relevant traces, logs, or otherwise.

**Expected behavior**
The App follows authorization_user_agent correctly, if unable to do so, throw correct error

**Actual Behavior**
authorization_user_agent is stuck at webview

**Screenshots**

**Additional context**
Please advice a way to clear any external caches of which the login module has so that it can reset and start recognise the correct setting of authorization_user_agent, it seems it stores additional information or things that hidden from user.

**Please note: Do not include sensitive information like PII, OII, credentials, secrets, and tokens.**

For **privacy/security** issues please see instructions [here](https://github.com/AzureAD/microsoft-authentication-library-for-android#security-reporting)

**Comment by hansheng654** [comment]
I traced the issue to a flag called mUseBroker, and realise it can be force set to false by setting broker_redirect_uri_registered in the config.. this is not documented anywhere but seems does the trick. this value is not set in my dev varient of the built yet it's false by default, in the prod flavour it is true by default..

Can someone with more experience help undertand how does it all work

**Comment by negoe** [comment]
@hansheng654 The flag mUseBroker that you discovered is part of the Microsoft Authentication Library (MSAL) for Android library. This flag controls whether MSAL uses a broker app for authentication. A broker app is a separate app that handles authentication on behalf of the main app. It can be Authenticator app or Company Portal. The broker app provides authentication experience by using single sign-on (SSO) and other features. Find more details S[SO through brokered authentication](https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-android-single-sign-on#sso-through-brokered-authentication)

When mUseBroker is set to true, MSAL will use the broker for authentication if there is one available on the device. When it is set to false, MSAL will use a webview for authentication instead of a broker app.

The broker_redirect_uri_registered flag that you found in the configuration is used to determine whether a broker app is registered with MSAL. If it is set to true, MSAL will try to use a broker app for authentication even if mUseBroker is false. If it is set to false, MSAL will not use a broker app even if mUseBroker is true.

By setting broker_redirect_uri_registered to false, you are telling MSAL not to use a broker app for authentication, even if one is available. This can help you avoid authentication issues that may be caused by a misconfigured broker app.
