### ISSUE TITLE
NFC permission request gets added when updating mSal version from 2.2.3 to 4.0.5

### ISSUE THREAD

**Issue by naquee-rizwan** [AzureAD/microsoft-authentication-library-for-android#1740]
Hi team,

After upgradation of mSal library version from 2.2.3 to 4.0.5, we detected mSal library is resolving dependencies to include the library :  **com.yubico.yubikit:android:2.1.0**

Further, this library is introducing the NFC permission as tracked via manifest merger report: <**uses-permission android:name="android.permission.NFC"**>

As we don't want to add one more permission under our bucket if it is not required, can you please help us out with the following queries :- 
1. What is the use case when workflows regarding NFC permission will be triggered?
2. Will it lead to any issue if we remove this permission from our Manifest? Will it lead to any crash / intermittent issues?
3. We hope that this resolved library (com.yubico.yubikit:android:2.1.0) is safe if it is newly added compared to 2.2.3 version?

Thanks.

**Comment by shoatman** [comment]
@melissaahn - FYI

**Comment by melissaahn** [comment]
Hi Naquee, 

Thanks for reaching out, and please see my answers below:

1. Certificate-based authentication with YubiKeys has recently been released for public preview within MSAL, so the YubiKit library was added to help facilitate this new feature. This means that users will be able to login to their Azure Active Directory accounts using a YubiKey. The YubiKey can be connected to an Android device via USB or NFC, although for public preview, MSAL offers USB connections only. We are currently working on NFC support as well (it's a highly requested feature) and we're aiming for its release in early 2023. For more information about CBA with YubiKey, please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-entra-azure-ad-blog/azure-ad-certificate-based-authentication-cba-on-mobile/ba-p/2365672).
2. As it seems this permission is added by the YubiKit library, I can't say I'm entirely sure what will happen if it's removed from your manifest, but after doing some searching I found this [Stack Overflow post](https://stackoverflow.com/questions/65516161/unfortunately-myapp-has-stopped-working-possible-due-to-nfc-permissions). And if it doesn't end up causing crashes, it will still be likely that Microsoft users depending on CBA for authentication will not be able to use their YubiKeys to authenticate into your app if they don't have the USB-C version. 
3. We have been directly communicating with the team at Yubico behind the YubiKit library throughout the development of this feature, and our testing so far hasn't brought up any major issues or concerns to note. We are still awaiting feedback from users since this feature is new. The library is open source, which you can find [here](https://github.com/Yubico/yubikit-android).

Let me know if you have any follow-up questions regarding the answers above. Regarding 2 and 3, I can also forward questions to Yubico if you would like more specific answers about their library.
