### ISSUE TITLE
Log full requests (url, header, payload)

### ISSUE THREAD

**Issue by unhammer** [AzureAD/microsoft-authentication-library-for-android#1787]
**Is your feature request related to a problem? Please describe.**

We're trying to upgrade our signin policy for use in our android app, but in the new version we're not getting an extra field that used to be there (a list of emails) from the refresh response, only the login response. But we do get it from our test client that uses

`https://foo.b2clogin.com/foo.onmicrosoft.com/oauth2/v2.0/authorize?p=B2C_1A_SIGNIN&client_id=…&nonce=defaultNonce&redirect_uri=https%3A%2F%2Fjwt.ms&scope=openid&response_type=id_token&prompt=login`

for login and the same without `&prompt=login` for refresh:

`https://foo.b2clogin.com/foo.onmicrosoft.com/oauth2/v2.0/authorize?p=B2C_1A_SIGNIN&client_id=…&nonce=defaultNonce&redirect_uri=https%3A%2F%2Fjwt.ms&scope=openid&response_type=id_token`

**Describe the solution you'd like**

It would be nice if we could log the exact urls this library uses so we can compare what's going wrong.

**Describe alternatives you've considered**

We're fetching tokens with `IMultipleAccountPublicClientApplication.acquireTokenSilentAsync`. I've tried

```java
import android.util.Log;
import com.microsoft.identity.client.Logger;
import com.microsoft.identity.client.ILoggerCallback;
…
        Logger.getInstance().setEnableLogcatLog(true);
        Logger.getInstance().setEnablePII(true);
        Logger.getInstance().setExternalLogger(new ILoggerCallback()
            {
                @Override
                public void log(String tag, Logger.LogLevel logLevel, String message, boolean containsPII)
                    {
                        Log.d("microsoftb2cuser", logLevel + ":" + tag + ":" + message);
                    }
            });
```

which logs things like `realm is not returned from server. Use utid as realm` but it shows no urls.

**Comment by negoe** [comment]
@unhammer, Need the following information so that I can help you better. 

- Can you please provide more information on the "extra field" that is missing in the refresh response? What is the name and purpose of the field, and how is it used in your app?
- How are you currently handling the login and refresh flows in your Android app? 
- Are you getting any issues in getting the token? 
- Have you checked the Azure AD B2C portal to ensure that the required claims are configured correctly in your user flow? Can you please check the config of your test v/s prod app to make sure they both have the same configuration?

**Comment by unhammer** [comment]
We managed to solve this by server-side logging instead. 

It still seems like it would be useful to be able to log the exact requests being sent from the client, but if "past me" is the only one who needs it I guess this issue can be closed :)
