### ISSUE TITLE
acquireToken returns an error "Missing required tokens of type: access_token" in callback with certains scopes but not when given the client ID

### ISSUE THREAD

**Issue by mariodigirolamo1** [AzureAD/microsoft-authentication-library-for-android#2028]
**Describe the bug**
We're trying to integrate Azure AD B2C in our Android app but when we try to acquire a token with different scopes we always get an exception with message `Missing required tokens of type: access_token` but when we use our Client/Application ID in place of the scope we are able to retrieve the token.

**Smartphone (please complete the following information):**
 - Device: SM-A515F
 - Android Version: Android 10, QP1A.190711.020.A515FXXU4CUA1
 - Browser: Chrome
 - MSAL Version: detected in 4.5.0 but occurs also in 5.0.1

**Stacktrace**
No crash occurs.

**To Reproduce**
When we use one of the following:
`.withScopes(listOf("https://graph.microsoft.com/openid"))`
`.withScopes(listOf("https://graph.microsoft.com/User.Read"))`
`.withScopes(listOf("https://graph.microsoft.com/.default"))`
We receive an exception in the callback with the following error message:
`Missing required tokens of type: access_token`

When we use our client ID in place of the scopes such as:
`.withScopes(listOf("<client_id>"))`
We are able to retrieve the token.

If you need more details from the configuration I can provide 'em.

**Expected behavior**
Be able to retrieve the token with the following scopes:
`.withScopes(listOf("https://graph.microsoft.com/openid"))`
`.withScopes(listOf("https://graph.microsoft.com/User.Read"))`
`.withScopes(listOf("https://graph.microsoft.com/.default"))`

and not with a client id.

**Actual Behavior**
We can't retrieve the token with the given scopes but via the client id.

**Additional context**
I tried following the [official doc for Android](https://learn.microsoft.com/en-us/entra/identity-platform/msal-android-b2c#interactively-acquire-a-token) and I expected to use something in the format of a URL such as "https://contoso.onmicrosoft.com/contosob2c/read" to retrieve the token and I don't seem to see any instance in which I can retrieve it by using the client ID.
I tried using the client id since after I spent a bit of time digging I found this [post](https://www.appsloveworld.com/azure/17/msal-android-missing-required-tokens-of-type-0-while-acquiretoken) but it gives no extra information on why it works and since I'm not an expert in this domain I'd like to get some source to understand why such behaviour happens.

**Comment by negoe** [comment]
@mariodigirolamo1  Did you add the admin consent for the API permission on Azure portal? 

You need to set the scope first.  This sample sets the scope as https://fabrikamb2c.onmicrosoft.com/helloapi/demo.read so that it can acquire an access token for this API.
Please [see](https://github.com/Azure-Samples/ms-identity-android-java/blob/f3627771277e9e61d2058c0496f5c732706fd10c/app/src/main/java/com/azuresamples/msalandroidapp/B2CConfiguration.java#L94) in the official sample code.

 public static List<String> getScopes() {
        return Arrays.asList(
                "https://fabrikamb2c.onmicrosoft.com/helloapi/demo.read");
    }

- If you haven't, create an app registration which represents your web API and expose the API by following [Quickstart: Configure an application to expose a web API](https://learn.microsoft.com/en-us/azure/active-directory/develop/quickstart-configure-app-expose-web-apis).
- Then add the API permission in your client app registration and configure  auth_config_b2c.json file.

**Comment by mariodigirolamo1** [comment]
Hi negoe, thanks for your answer!

Yes, I did grant admin consent for the APIs (tho I also see that for Microsoft Graph `offline_access` and `openid` it isn't required).

On the Android side I did set the scopes while acquiring the token also the configuration file is correctly setup as per documentation.

A colleague exposed a custom API and that one worked when set as scope.

The starting issue and doubt stay there, tho:

1. Still can't use the **graph.microsoft.com** scopes reported above to get a token 
2. Still don't know why we were able to retrieve a token by using the `client_id` in place of a scope, so like this 
`.withScopes(listOf("<client_id>"))`

Anyway, we've been able to make progress exposing the API in the meantime and thank you for your support!
