### ISSUE TITLE
OpenTelemetry: Document what information is collected and allow opt-out

### ISSUE THREAD

**Issue by mtotschnig** [AzureAD/microsoft-authentication-library-for-android#2129]
**Is your feature request related to a problem? Please describe.**
Users of my app want to know why it depends on OpenTelemetry: https://github.com/mtotschnig/MyExpenses/issues/1523. I would love to be transparent about what information is collected by MSAL and ideally offer the option to opt-out.

**Describe the solution you'd like**

- Documentation of how OpenTelemetry is used by this library.
- An option that can be set in the config file or via a parameter that would allow to prevent any logging via OpenTelemetry.

**Comment by shahzaibj** [comment]
Hi @mtotschnig Currently MSAL does NOT collect any telemetry data. The open telemetry has two parts: API (instrumentation layer) and SDK (export layer). MSAL currently is only using the API to instrument the code. The SDK part is never used in MSAL. Without the SDK part the data is never exported and all instrumentation from the API essentially becomes NO-OP without an SDK integrated. 

A customer application can potentially take a dependency on SDK and register their own exporter and in that case the data may be collected and transported to customer's own backend/storage and in that case they will own the data. This is the only way the data can be collected from MSAL today and if a customer has configured this then we provide no support for any issues arising in this layer because this would be their own code/solution. 

As things stand today, MSAL doesn't export any telemetry data by default and there is no advertised support for any 3p integration for data export. 

I hope that helps.

**Comment by mtotschnig** [comment]
Thanks @shahzaibj !
