### ISSUE TITLE
Customize browser selection logic

### ISSUE THREAD

**Issue by danieldobalian** [AzureAD/microsoft-authentication-library-for-android#306]
Today, the browser selection logic in MSAL is deterministic and not extensible. Should there be extensibility points for app developers to override the logic to customize the selection heuristic?

**Comment by heidijinxujia** [comment]
The discussion is still in the air.
And the current implementation is to check the Authority type of the request authority. 
1. If the AuthorityType is B2C, the authentication activity will use the system browser.
2. Otherwise, MSAL will use embedded webview as default.

There is also a proposal across platforms, which will be discussed next Wed meeting. The proposal will be
1. Add property Authentication Configuration in the PublicClientApplication
2. Authentication Configuration maintains the webview selection, which could be , for example,
{EmbeddedWebview (default), SystemBrowser, CustomTab}
3. The B2C developer need to set the AuthenticationConfiguration.WebviewSelection to SystemBrowser or CustomTab explicitly if they want to use the system browser.
4. Additional authority validation will be add to avoid the conflict btw AuthenticationConfiguration.WebviewSelection and the request authoriy.

**Comment by heidijinxujia** [comment]
I did a E2E investigation on this issue. Please check the email thread `B2C MSAL System Browser Investigation` where I shared my investigation result and thoughts on the implementation.

**Comment by iambmelt** [comment]
Guidance on authorization agents can be found here:
https://docs.microsoft.com/en-us/azure/active-directory/develop/authorization-agents
