### ISSUE TITLE
Release 0.2.0

### ISSUE THREAD

**Issue by Glennmen** [AzureAD/microsoft-authentication-library-for-android#395]
I see that there is already an [Migrating from MSAL.Android 0.1.n to 0.2.0](https://github.com/AzureAD/microsoft-authentication-library-for-android/wiki/Migrating-from-MSAL.Android-0.1.n-to-0.2.0) wiki page but the 0.2.0 version of this Library has not been released yet.

Is it possible to get a timeframe for the release? Like days, weeks, months, ...
I really need this version for a clients project, because they make custom android devices that don't have Chrome build in. The current library version requires Chrome.
The next version (from what I understand) supports other browser (or webviews) and this should fix my current issue.

Thanks for any info you can provide me.

**Comment by danieldobalian** [comment]
You can expect the release in the next few days, potentially late this week!

You are absolutely correct, the next version will support all browsers.  We've also added support for in-app WebViews.  Once it drops, please do let us know your experience upgrading and using browsers other than Chrome.

**Comment by danieldobalian** [comment]
We're working on an article that addresses this, fyi @heidijinxujia. 

The primary difference is:
1. User Experience
2. SSO benefits.

**User Experience**

In WebViews, you can highly customize the user experience and it always feel like the user is operating inside the app. Browsers will be more limited in this sense.  In cases it launches a Custom Tab (if the browser supports it ie. Chrome, Samsung, and a few others) it's fairly customizable and feels in-app, but in the scenario the user's default browser doesn't support custom tabs, the look/feel will be that of their browser and it may feel like they're switching apps. 

**SSO Benefits**

Using the browser signfiicantly improves SSO on the device as cookies can be shared across apps. Rather than Azure AD // MSA // Azure AD B2C setting the cookie scoped to an app, the browser allows it to be scoped to the browser. This means if the user signs in to one app, they then have the opportunity for any app down the line (that uses the same browser) to get "interactive SSO" where they would select their account but not required credentials. 

The other cool benefit is SSO between native apps and web apps. If the user signs into the Outlook web app, they could benefit from SSO in the Outlook mobile app (and vice versa). 

WebViews will be significantly limited in this regard. We're working on some other techniques that will deliver some form of SSO to apps using in-app WebViews, but it's a ways out.  

Let me know if you have any other questions! Update on the release is the code is signed off / passed all automated testing, you can see it in the release/0.2.0 branch. We're going to begin executing the release shortly.

**Comment by Glennmen** [comment]
I see version 0.2.0 is added on Maven Central but I don't see a release here on Github (or has the README.md been updated).
Is this version on Maven Central good to use or should I wait till a release has been made on Github?

**Comment by iambmelt** [comment]
@Glennmen The version on Maven Central is good to go! Typically we see a 3-6 hour delay between when we deploy and when we start seeing our binaries available on Maven. Because of this, we usually wait to post the release announcement until we're confident users can resolve the binaries successfully.

The release posting will be updated today - cheers 😎

**Comment by danieldobalian** [comment]
Closing this issue since it's available on Maven. As Brian said, doc updates roll in slowly thereafter.
