### ISSUE TITLE
Clear SSO token

### ISSUE THREAD

**Issue by Glennmen** [AzureAD/microsoft-authentication-library-for-android#426]
Once a user disconnects (`removeAccount()`) the SSO token is still valid in the webview and will be shown on next sign in. I can't find any function to clear webview cookies/data.
This isn't very safe for shared devices, my use-case.

I did find this issue #185, has it been implemented? Any idea about the timeframe for this feature. Or a temporary solution that might work for me?

Thanks!

**Comment by shoatman** [comment]
@Glennmen - There's a pretty active discussion about what the experience should be for signing out of a device.  For example: Should any application on the device be able to initiate a device signout request and what should the UX experience for such an operation be.  I'm adding @danieldobalian and will forward him your question/comment.  This is work in progress for us still.... so your feedback would be appreciated.

**Comment by Glennmen** [comment]
I understand what you are saying.
My suggestion: Only for webview, as webview can be considered to be sandboxed for the app only and not system wide like a browser. Add an option to use webview in "private mode" so that it doesn't keep any cookies.
An example of what I mean: https://stackoverflow.com/a/9838963/7446162

**Comment by shoatman** [comment]
We'll have to review our scenarios.  I suspect that some scenarios are enabled/improved by having the cookies present.  I'm thinking in terms of step up authentication.  I think i'd prefer to remove an account's specific cookie as a result of removeAccount.... since this is likely the same experience that device browsers require.  With that said.  I'm also open to the possibility of making this configurable for webview.  In your use case you may not need the scenarios that I mentioned and it certainly doesn't hurt to try it.  

Is your application a single account or multi-account application?  Said another way... can only one account be in use at a time.... or can a user have multiple accounts signed in at once inside your app?  I'm asking since some of this is simpler when the app in question only ever has one account signed in at a time.

**Comment by Glennmen** [comment]
@shoatman I will try to explain my use-case. 
The app itself is a whiteboard app that is installed on big touch screen devices that are used in schools or in meeting rooms. I use MSAL and Microsoft Graph for the build in email export feature.
In the app I have a `remember logged in user` option that will keep the access token for future use. But in most cases as most devices will be in shared rooms I think people want their account info removed after export (removeAccount).

**Comment by shoatman** [comment]
Thanks @Glennmen.  Knowing about the shared devices scenario is also helpful.  Daniel and I will talk this over.  In your case it's likely that your users will not experience step up.... since you're accessing a single resource that has the potential to be protected by a conditional access policy (require MFA, compliant device).  The policy would be evaluated on the first request.  It also sounds like it only makes sense to have one account currently signed in... so that opens some other options.  Thanks

**Comment by Glennmen** [comment]
I hate being "that guy" but any progress on this or is it still in the discussion phase? 
I tried looking into it myself and ended up in the `microsoft-authentication-library-common-for-android` repo but was quickly lost there lol, damn so many files.

**Comment by Glennmen** [comment]
Any update about this scenario? Current version remembers user credentials on the login page and this might be a security/privacy issue for my clients and will probably delay the release of the next version.
