### ISSUE TITLE
AuthenticationResult should implement an interface or be non-final for unit test mocking.

### ISSUE THREAD

**Issue by wyber** [AzureAD/microsoft-authentication-library-for-android#470]
I'm attempting to write a unit test against some code that uses AuthenticationResult. This class is final, so I can't mock it. It doesn't implement an interface, so I can't depend on that instead.

The AuthenticationResult takes an interface in the ctor(ICacheRecord) so I can potentially mock that but the ICacheRecord has 4 more classes I need to mock.

**Comment by iambmelt** [comment]
Thanks for your feedback, @wyber -- we'll incorporate this feedback into a future release.

@danieldobalian FYI ^^

**Comment by iambmelt** [comment]
In the meantime to work around this, you could consider using a library like PowerMock, assuming it suits your purposes.

I will mention, our dev team has had issues in the past integrating PowerMock into the same project as Mockito due to namespace collisions and versioning issues: something to be aware of if you go this route.

**Comment by wyber** [comment]
Powermock slows tests significantly. We avoid it by instead writing our own interfaces and wrapping MSAL classes in our own implementations of those interfaces.
Ex.
```
interface IAuthResult {
....
}

class AuthResult(private val AuthenticationResult) : IAuthResult {
}
```

**Comment by iambmelt** [comment]
Public API is now using [`AuthenticationCallback`](https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/dev/msal/src/main/java/com/microsoft/identity/client/AuthenticationCallback.java) interface
