### ISSUE TITLE
Dynamic Client Id MSAL Android app

### ISSUE THREAD

**Issue by saqibmirza2007** [AzureAD/microsoft-authentication-library-for-android#530]
The Client Id/ App id is bind in Android manifest which cannot be changed @ runtime and my requirement is to set Client Id for different users via api. Is there a way around. I have also check the one with config file but the login auth returns via Deep LInk

**Comment by danieldobalian** [comment]
Hey @saqibmirza2007, 

Can you elaborate on this requirement? The Microsoft identity platform (Azure AD v2.0) is designed to be used by 1 app ID across various platforms.  To this end, I'd be hesitant to formalize this pattern into MSAL. 

If the the scenario calls for this, we can further the discussion of supporting it. Mind helping us understand?

**Comment by saqibmirza2007** [comment]
Hi @danieldobalian,
Thanks for response. We have a scenario that we ha different clients using our app with different server deployments so in case AzureAD we have also different AD deployments per user base with different apps and for that need we have to execute login for app via server response so that's the issue and we want to sort out this wth MSAL as we have also some other Microsoft integrations .
Thanks

**Comment by dkkristina** [comment]
We also have this scenario. Hope this gets added in the future! :)

**Comment by shrutisharanjda** [comment]
we also have this requirement , please update once this feature is added

**Comment by papafe** [comment]
We also have the same use case, with our customers deploying their own installations.

**Comment by alitaimoor1415** [comment]
we also have the same requirement. kindly update this feature and let us know when the feature is added. Thanks

**Comment by MarcelWinkelEBF** [comment]
Is there any progress on this? Cannot believe that it is not the standard implementation to use a dynamic clientId..

**Comment by MarcelWinkelEBF** [comment]
@danieldobalian @iambmelt can someone from you guys take a look into this issue? and some feedback? here are some guys - including me - who would need that asap. Or you could give us a workaround idea?

**Comment by saqibmirza2007** [comment]
> @danieldobalian @iambmelt can someone from you guys take a look into this issue? and some feedback? here are some guys - including me - who would need that asap. Or you could give us a workaround idea?

@MarcelWinkelEBF you can use ADAL module from Microsoft com.microsoft.aad:adal we are currently using this for iOS and Android Apps

**Comment by MarcelWinkelEBF** [comment]
> > @danieldobalian @iambmelt can someone from you guys take a look into this issue? and some feedback? here are some guys - including me - who would need that asap. Or you could give us a workaround idea?
> 
> @MarcelWinkelEBF you can use ADAL module from Microsoft com.microsoft.aad:adal we are currently using this for iOS and Android Apps

Yes that is true. That's working and I'm sure we had this module before (but with an older version). We wanted to switch to MSAL for a better implementation. And I guess the same dynamic clientId flow should also work for MSAL. The custom redirectUri works fine for ADAL but not for MSAL. So the question is why to restrict it that much.

**Comment by osmanmz** [comment]
Can the library be brought in line with the parameters for objective C, swift and C#
Please advise if the issue will be address with issue: #797 opened on Oct 7, 2019 by Nasicus:
Allow passing of an object or string instead of a File to the PublicClientApplication creation methods?
For the other libraries: iOS and windows: ClientID is a parameter, why is Android using a file a a parameter instead of ClientID:
e.g. 
https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-mobile-app-configuration
Android Java uses R.raw.auth_config :
PublicClientApplication sampleApp = new PublicClientApplication(
                    this.getApplicationContext(),
                    R.raw.auth_config);

But the rest are as follows:
iOS Objective C:
NSError *msalError = nil;
     
MSALPublicClientApplicationConfig *config = [[MSALPublicClientApplicationConfig alloc] initWithClientId:@"<your-client-id-here>"];    
MSALPublicClientApplication *application = [[MSALPublicClientApplication alloc] initWithConfiguration:config error:&msalError];

Swift:
let config = MSALPublicClientApplicationConfig(clientId: "<your-client-id-here>")
if let application = try? MSALPublicClientApplication(configuration: config){ /* Use application */}

C#:
IPublicClientApplication application = PublicClientApplicationBuilder.Create(clientId)
  .ParentActivityOrWindowFunc(() => parentUi)
  .Build();

C# Android:
// Requires MSAL.NET 4.2 or above
var pca = PublicClientApplicationBuilder
  .Create("<your-client-id-here>")
  .WithParentActivityOrWindow(() => CrossCurrentActivity.Current)
  .Build();

**Comment by larsbj** [comment]
This is a showstopper for us. We develop an app that we distribute via App Store, and the customers must be free to select which Azure AD app registration to use and trust. Any plans for supporting a dynamic client id for Android?

**Comment by iambmelt** [comment]
@larsbj This is [already supported](https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/dev/msal/src/main/java/com/microsoft/identity/client/PublicClientApplication.java#L330-L374) - my apologies, this ticket was never updated to reflect this fact.

**Comment by robertlinsener** [comment]
Using dynamic ClientId for creation of `PublicClientApplication` is working, but what about `redirectUri` in `Manifest`? It is not possible to change it on runtime.

**Comment by bgraham1962** [comment]
@iambmelt This linked piece of code does allow the client id to be passed as a parameter to the PublicClientApplicationBuilder.Create method but does it get around the need to hard code the Client Id in the intent that receives the MSAL return url?  

This still appears to be needed either in a manifest defined intent or in the attributes of a coded intent.

`
<activity android:name="microsoft.identity.client.BrowserTabActivity" android:configChanges="orientation|screenSize" android:exported="true">
      <intent-filter>
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data android:scheme="msal[**REPLACE THIS WITH THE CLIENT ID OF YOUR APP**]" android:host="auth" />
      </intent-filter>
    </activity>
`

Regards
Brian

**Comment by Suraj820** [comment]
hello,  did any one found the solution for this??

**Comment by bgraham1962** [comment]
Hi @Suraj820, 

The answer I came up with was to seperate the client Id from the Return Url.  I made a unique custom return url that I used for all Android installations and added that to both the Azure configuration and the Android manifest. With the changes above you can now pass the relevant Client Id into the Create method and this can be from settings.

Hope that helps
Brian
