### ISSUE TITLE
Adding resources to aquiretoken

### ISSUE THREAD

**Issue by Irfan21** [AzureAD/microsoft-authentication-library-for-android#532]
Hi,

I have a problem in accessing our organization API. If i add App ID uri in scope, it throws error saying AADSTS50001: The application named <app url> was not found in the tenant named <tenanat id>

Because of this i have tried alternatively to add resource in extraqueryparameter as

`
final static String SCOPES [] = {"openid offline_access https//graph.microsoft.com/user.read"};// Scope //should not be empty

pairList.add(new Pair("resource","web API client id"));

 sampleApp.acquireToken(getActivity(), SCOPES, "Login Hint", uiBehaviour, pairList, getAuthInteractiveCallback());
`
I get following error in browser activity

AADSTS901002: The 'resource' request parameter is not supported.

Please suggest me way to to access organization API's. Or adding web api client ID as a audience.

Thanks in advance.

**Comment by shoatman** [comment]
With the move to Microsoft Identity platform (formerly known as AAD v2 endpoint) you'll need to use scopes rather than resources.  To simplify the migration the service introduce the ability to take your existing resourced id/app id uri and append /.default to the end of your resource id and submit that as the scope that you would like.  This scope will provide you equivalent behavior that you would have seen with ADAL and the AAD v1 endpoint.

**Comment by shoatman** [comment]
@danieldobalian - I'd like to add resource id to the request parameters object to simplify the migration from ADAL to MSAL for those who do not need to support incremental consent.

**Comment by danieldobalian** [comment]
I think that would be a nice API - would it translate down to `resource/.default`?

**Comment by iambmelt** [comment]
See https://github.com/AzureAD/microsoft-authentication-library-for-android/pull/594

A resource can now be provided to `AcquireTokenParameters` to simplify the migration from ADAL to MSAL
