### ISSUE TITLE
Getting silent token even after password change in AD

### ISSUE THREAD

**Issue by suresh777** [AzureAD/microsoft-authentication-library-for-android#727]
Actually i am checking changing password feature. I changed my password in azure directory, After that i tried silent token it is providing token. But it should throw some error like authentication failed. Is it expected behaviour?

**Comment by iambmelt** [comment]
Hi @suresh777 

Yes, this is expected behavior.

When a password change event occurs, the refresh token for the specified account is revoked but the access token is not.

Depending on validity period of the access token (usually 1 hour, some apps increase to 24 hours) the access token will continue to work and be accepted by resource servers until its expiry. After the access token expires, MSAL will attempt to the use the refresh token to renew the access token - because the password will have changed causing the refresh token to be rejected, at that point you will be prompted to reauthorize.
