### ISSUE TITLE
ApiDispatcher NullPointerException

### ISSUE THREAD

**Issue by Poweryong** [AzureAD/microsoft-authentication-library-for-android#765]
**com.microsoft.identity.common.internal.controllers.ApiDispatcher.completeInteractive (ApiDispatcher.java:248)**
com.microsoft.identity.client.BrowserTabActivity.onResume (BrowserTabActivity.java:76)

This what i get from the crash report.

**Comment by iambmelt** [comment]
@Poweryong what build number are you using? device? android version?

**Comment by Poweryong** [comment]
Build number : 0.3.2-alpha
Device : Mi A2 Lite, Android 9
Device : Oppo F9, Android 8.1 
Device : Oppo A1691, Android 5.1

**Comment by iambmelt** [comment]
Thanks @Poweryong -- is there any more of this stacktrace you can share? More lines?

**Comment by Poweryong** [comment]
com.microsoft.identity.common.internal.controllers.ApiDispatcher.completeInteractive (ApiDispatcher.java:248)
com.microsoft.identity.client.BrowserTabActivity.onResume (BrowserTabActivity.java:76)
android.app.Instrumentation.callActivityOnResume (Instrumentation.java:1413)
android.app.Activity.performResume (Activity.java:7292)
android.app.ActivityThread.performResumeActivity (ActivityThread.java:3779)
android.app.ActivityThread.handleResumeActivity (ActivityThread.java:3819)
android.app.servertransaction.ResumeActivityItem.execute (ResumeActivityItem.java:51)
android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:145)
android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:70)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1811)
android.os.Handler.dispatchMessage (Handler.java:106)
android.os.Looper.loop (Looper.java:193)
android.app.ActivityThread.main (ActivityThread.java:6694)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:858)

So far only top 2 line, other is android.app .

**Comment by iambmelt** [comment]
Transferring over to @kreedula for follow-up. I suspect this has already been fixed on our `dev` branch

**Comment by kreedula** [comment]
This is fixed in `dev` branch here : https://github.com/AzureAD/microsoft-authentication-library-common-for-android/blob/dev/common/src/main/java/com/microsoft/identity/common/internal/controllers/ApiDispatcher.java#L371

A new version of MSAL will be releasing shortly(next week ) which will have the fix

**Comment by iambmelt** [comment]
Thanks @kreedula - we are not planning to ship a hotfix for our preelease `0.3.2-alpha` before our next release so I am going to close this issue

@Poweryong Please reach out if you have any major concerns, otherwise please plan to pick up our next release. Be advised it will contain API breaking changes
