### ISSUE TITLE
Need a version to use for support library Android

### ISSUE THREAD

**Issue by asterehin** [AzureAD/microsoft-authentication-library-for-android#788]
I see that there are some plans to release NoAndroidX version, but according to the latest commit - it's RC9 yet.
![image](https://user-images.githubusercontent.com/52634702/66138538-78f51d00-e607-11e9-93ed-89398e6506bc.png)

I need this urgently, as our iOS app already moved to MSAL but Android can't because there is no library with support library support.

**Comment by asterehin** [comment]
I see that there are some plans to release NoAndroidX version, but according to the latest commit - it's RC9 yet. 
![image](https://user-images.githubusercontent.com/52634702/66137960-8b228b80-e606-11e9-823c-0f55b1f99ec9.png)
I need this urgently, as our iOS app already moved to MSAL but Android can't because there is no library with support library support.

**Comment by iambmelt** [comment]
@asterehin There are currently no plans to create a public release of MSAL with AndroidX support _removed_.

Is there a reason you can't update your app to use the new androidx support packages?

**Comment by asterehin** [comment]
> @asterehin There are currently no plans to create a public release of MSAL with AndroidX support _removed_.
> 
> Is there a reason you can't update your app to use the new androidx support packages?

The reason is that we have tens of quite big apps and core library which are using support library. Migrate to androidX will take quite a lot of time and for now the only reason is that we wanted to 
Can you please advise what we can do?

**Comment by iambmelt** [comment]
@asterehin I see; that's a challenging circumstance.

So unfortunately, maintaining two forks of MSAL (one _with_ AndroidX and one _without_) isn't a sustainable development model for us so, aside from simply saying 'update to AndroidX' here's what you _could_ do:

I have pushed up a branch of our `1.0.0` release with no AndroidX support --  please note that this will **not** be maintained and no support will be given as it is **not** an official release.

**_Use at your own risk_.**

You can find the branch here:
https://github.com/AzureAD/microsoft-authentication-library-for-android/tree/iambmelt/unofficial-1.0.0-NoAndroidX

You can clone this branch and compile MSAL into your project.

Please note that this branch has a specific _submodule commit dependency_: `common@d3961461f2337dfe48dd2a5f42378a37cc810446`

If you want to clone this you can do the following:
```shell
> git clone --recurse-submodules -b iambmelt/unofficial-1.0.0-NoAndroidX https://github.com/AzureAD/microsoft-authentication-library-for-android.git
```

If you elect to go this route, I suggest opening this project in its own workspace and producing an `.aar` to embed in your application rather than take an entire source drop. Also note you may need to exclude MSAL files from ProGuard depending on how you're compiling. I won't provide instructions on how to do all that here as instructions on building a release `aar` are abundantly available on the internet. 

And with that, I am going to go ahead and close this issue -- best of luck :)

**Comment by asterehin** [comment]
Thanks for your reply! Will discuss with my managers now

**Comment by 4gus71n** [comment]
I'm curious about why to move to AndroidX. I did the migration in order to update to the 1.0 version a couple of days ago.

So far so good, but I don't understand the need of having a third-party library to migrate to AndroidX. I mean if a developer wants to use AndroidX on his project he can always enable the jetifier option on Gradle and have the third-party binary use AndroidX.

**Comment by RootFengshun** [comment]
Have came across same problem-- just need integrate msal into a very old project (just for temp demo). Thanks @asterehin  for the private branch. It works well for me. We are considering upgrade our project.
