### ISSUE TITLE
authority parameter is @NotNull but null is passed in documentation

### ISSUE THREAD

**Issue by mattlaabs** [AzureAD/microsoft-authentication-library-for-android#792]
In step 4.3 of the readme NULL is passed for the `@RecentlyNonNull` authority parameter.
I am successfully using https://login.microsoftonline.com/common/v2.0 instead, but does this cover all supported account types? Please update the docs and provide the broadest possible authority as constant (or as default and make the parameter `@Nullable` again).

**Comment by iambmelt** [comment]
@mattlaabs Thanks for calling out this miss in the docs -- #794 corrects this for the "base case" where a user is renewing a token for their _home account_ and will merge shortly.

Regarding your question about using the 'broadest possible authority': sadly it is not that simple: because an `IAccount` may contain one more `TenantProfiles` which span multiple tenants and, by extension, multiple authorities, there is not a single universal authority which unambiguously authorizes _any TenantProfile_.

Authorities such as `/common`, `/consumers` or `/organizations` are _aliases_ for a users home tenant and so they cannot be used to renew tokens for [guest users](https://docs.microsoft.com/en-us/azure/active-directory/b2b/user-properties). Additionally, these endpoints currently cannot be used at all with [B2C applications](https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-overview).

For more information about Accounts and Tenant Profiles please consult [this documentation](https://docs.microsoft.com/en-us/azure/active-directory/develop/accounts-overview) which provides some conceptual and practical context.
