### ISSUE TITLE
Can app get informed of account switching when single sign on?

### ISSUE THREAD

**Issue by RootFengshun** [AzureAD/microsoft-authentication-library-for-android#851]
I user getCurrentAccountAsync() when activity resume to sync whether the AAD is signed on/out.
I wonder if there is a way to get informed when my app is in background?

**Comment by rpdome** [comment]
Hi,

I assume that you're referring to the Global Sign out functionality.

Currently, we do not have such capability. Our concern is that such mechanism might strain user's device (i.e. every registered app will be invoked, and do their operation - which we do not know how heavy they are - at the same time).

If we can find the way that such thing would not happen, we might pick this up in the future.

Thanks,
Dome

**Comment by RootFengshun** [comment]
Thanks for your timely reply! About the global sign out, I also wonder that if my app signs out,  and other 3rd party app doesn't execute "getCurrentAccountAsync", can they call graph API without signing in again? Is there some mechanism like clearing token to ensure security? How does it work?
Thanks, 
Shun

**Comment by rpdome** [comment]
We clear every token and cookies on our end on sign out. However, if somehow those apps are caching tokens on their end, then those tokens will still be valid. We ask apps that supports global sign out to invoke getCurrentAccountAsync() so that they can take care of this scenario on their end.

Feel free to ping me directly via teams or email (my alias is rapong).

Thanks,
Dome
