### ISSUE TITLE
Connection is not available to refresh token because power optimization is enabled. And the device is in doze mode or the app is standby

### ISSUE THREAD

**Issue by slowcar** [AzureAD/microsoft-authentication-library-for-android#998]
Using msal 1.4.0

Our app uses Workmanager to synchronize in fixed intervals.
When the device is not used the worker fails to retrieve a valid token with a client exception:

> com.microsoft.identity.client.exception.MsalClientException: Connection is not available to refresh token because power optimization is enabled. And the device is in doze mode or the app is standby

Is there an option to enable token retrieval with power optimization active? Our worker creates network connections just fine with accounts that don't use modern auth.

I am also unable to find the error code for the MsalClientException, DEVICE_NETWORK_NOT_AVAILABLE and IO_ERROR are handled separately, everything else sets the account to invalid and requires user interaction.

**Comment by slowcar** [comment]
I have disabled power optimization for our app on several test devices and still get the same error message.
We really need the auth library to work reliable in all device states.

**Comment by slowcar** [comment]
I have wrapped the aquireTokenSilent call with a wakelock, issue still persists.
All my test devices below Android 10 do not show this behavior, it seems to be related to the more aggressive power management on 10. I have not been able to reproduce the behavior with a simulator and adb commands like adb shell dumpsys deviceidle force-idle.

`PowerManager powerManager = (PowerManager) MEDApplication.getInstance().getSystemService(Context.POWER_SERVICE);
PowerManager.WakeLock wakeLock = null;
if (powerManager != null) {
	 wakeLock = powerManager.newWakeLock(PowerManager.PARTIAL_WAKE_LOCK, "MyApp:ModernAuthUtil");
	 wakeLock.acquire(2000);
}
IAuthenticationResult result = clientApplication.acquireTokenSilent(SCOPES, account, authority);
if (wakeLock != null) {
	wakeLock.release();
}`

I have found the relevant code in the DefaultConnectionService::isNetworkDisabledFromOptimizations

`/**
 * Determines if the client app cannot access the network due to power saving optimizations introduced in API 23.
 *
 * @return true if the device is API23 and one or both of the following is true: the device is in doze or the company
 * portal is in standby, false otherwise.
 */
@TargetApi(Build.VERSION_CODES.M)
public boolean isNetworkDisabledFromOptimizations() {
	if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
		final UsageStatsManagerWrapper usageStatsManagerWrapper = UsageStatsManagerWrapper.getInstance();
		if (usageStatsManagerWrapper.isAppInactive(mConnectionContext)) {
			Telemetry.emit((BaseEvent) new BaseEvent().put(TelemetryEventStrings.Key.POWER_OPTIMIZATION, String.valueOf(true)));
			return true;
		}

		final PowerManagerWrapper powerManagerWrapper = PowerManagerWrapper.getInstance();
		if (powerManagerWrapper.isDeviceIdleMode(mConnectionContext) && !powerManagerWrapper.isIgnoringBatteryOptimizations(mConnectionContext)) {
			Telemetry.emit((BaseEvent) new BaseEvent().put(TelemetryEventStrings.Key.POWER_OPTIMIZATION, String.valueOf(true)));
			return true;
		}
	}

	Telemetry.emit((BaseEvent) new BaseEvent().put(TelemetryEventStrings.Key.POWER_OPTIMIZATION, String.valueOf(false)));
	return false;
}`

The second call resolves to
`/**
 * Wrap the final class function UsageStatsManager.isAppInactive(). And make the code testable.
 *
 * @param connectionContext Context used to query app active state.
 * @return true if the app is inactive.
 */
@TargetApi(Build.VERSION_CODES.M)
public boolean isAppInactive(final Context connectionContext) {
	return ((UsageStatsManager) connectionContext.getSystemService(Context.USAGE_STATS_SERVICE)).isAppInactive(connectionContext.getPackageName());
}`

see https://github.com/AzureAD/microsoft-authentication-library-common-for-android/blob/dev/common/src/main/java/com/microsoft/identity/common/adal/internal/net/DefaultConnectionService.java

**Comment by slowcar** [comment]
It seems that UsageStatsManager.isAppInactive is the culprit.
The underlying issue would be that the androidx.WorkManager decides that now is a good time to run our background worker but does not change the usagestats, maybe because they are only intended for real user interaction.

What i do not understand is why the MSAL library needs to check this before trying to make a network connection. I would suggest that this check is dropped from the library as using modernauth in background processes is a valid use case even if the user has not interacted with the app for the system defined time it takes for isAppInactive to return true.

Should i create a new issue on the shared/common github project?

**Comment by kreedula** [comment]
We have removed `UsageStats` check and added a boolean to  config to disable the check. You can add `power_opt_check_for_network_req_enabled: false` to config to disable this check

 please see : https://github.com/AzureAD/microsoft-authentication-library-common-for-android/pull/894

**Comment by masztalski** [comment]
Hi, I'm using latest version 4.2.0 and issue still is occurring. 
I have logic in app that when app should execute network call is checking with Authenticator from okhttp3 if expiraration date of token is still valid. If token is considered as expired app is executing silent authentication before next call. Below is snippet from my logs
![image](https://user-images.githubusercontent.com/11578875/224664913-b50ac680-f724-47f1-9b6e-93d2430c1307.png)
From it you can see that on 10:07:45:338 app receives request for executing API call, during next few seconds app is trying to refresh token and receives exception about power optimization. I have skipped next logs where there are another approaches to refresh token. Each time same message received:
`com.microsoft.identity.client.exception.MsalClientException: Connection is not available to refresh token because power optimization is enabled. And the device is in doze mode or the app is standby at com.microsoft.identity.client.internal.controllers.MsalExceptionAdapter.msalExceptionFromBaseException(MsalExceptionAdapter.java:24) at com.microsoft.identity.client.SingleAccountPublicClientApplication$3.onError(SingleAccountPublicClientApplication.java:2) at com.microsoft.identity.client.SingleAccountPublicClientApplication$3.onError(SingleAccountPublicClientApplication.java:1) at com.microsoft.identity.common.java.controllers.CommandDispatcher.commandCallbackOnError(CommandDispatcher.java:15) at com.microsoft.identity.common.java.controllers.CommandDispatcher.access$900(CommandDispatcher.java:1) at com.microsoft.identity.common.java.controllers.CommandDispatcher$4.run(CommandDispatcher.java:47) at android.os.Handler.handleCallback(Handler.java:751) at android.os.Handler.dispatchMessage(Handler.java:95) at android.os.Looper.loop(Looper.java:154) at android.app.ActivityThread.main(ActivityThread.java:6151) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779) Caused by: com.microsoft.identity.common.java.exception.ClientException: Connection is not available to refresh token because power optimization is enabled. And the device is in doze mode or the app is standby at`

I have logs for tracking network availability and there is no information about loosing network connection.
